package com.inscopelabs.abx.xtools.plugins.sdk.api

import android.content.Context
import android.webkit.WebView

/**
 * The contract every XTools plugin must satisfy. Plugins are sandboxed
 * JavaScript / HTML / CSS bundles that run inside a host-managed [WebView].
 *
 * Implementations are usually generated by the Plugin Studio from a
 * [com.inscopelabs.abx.xtools.plugins.sdk.templates.Template], but a plugin
 * can also be hand-authored and loaded through [PluginLoader].
 *
 * Lifecycle mirrors Android's own: [onLoad] -> [onResume] -> [onPause] ->
 * [onDestroy]. The host drives this — plugins must not call these on
 * themselves.
 */
interface Plugin {

    /** Stable, unique plugin id (e.g. `com.example.hello-world`). */
    val id: PluginId

    /** Human-readable name shown in the toolbar / launcher. */
    val displayName: String

    /** Declared manifest. Validated at install time. */
    val manifest: PluginManifest

    /**
     * Bind this plugin to a [WebView] and an Android [Context]. Called once
     * when the plugin is loaded. Implementations should set up the
     * `@JavascriptInterface` bridge here, not in the constructor.
     */
    fun onLoad(context: Context, host: PluginHost)

    /** Called when the host activity becomes interactive. */
    fun onResume()

    /** Called when the host activity loses focus but is not destroyed. */
    fun onPause()

    /**
     * Called when the plugin is being permanently removed. Implementations
     * should detach JS interfaces, clear listeners, and free native handles.
     */
    fun onDestroy()
}

/**
 * The host application surface exposed to a plugin. Anything the plugin is
 * allowed to touch goes through here, so the bridge layer can enforce
 * permission gating in one place.
 */
interface PluginHost {
    /** The [WebView] the plugin renders into. */
    val webView: WebView

    /** A process-stable id used for logging and storage scoping. */
    val instanceId: String

    /**
     * Post a [PluginEvent] back to the host. The host forwards these to the
     * [com.inscopelabs.abx.xtools.plugins.debug.LogBridge] when one is
     * attached, otherwise drops them silently.
     */
    fun emit(event: PluginEvent)

    /**
     * Resolve a resource from the plugin bundle (e.g. `assets/icon.png`).
     * Returns `null` if the asset is missing — the validator should have
     * caught that at install time, so a `null` here indicates a stale
     * install.
     */
    fun asset(path: String): ByteArray?
}
